// generated by mlgn.netlist.verilog — 2 PIs, 0 state bits, 16 gates, 16 outputs
module lgn_ops (
    input  wire clk,
    input  wire rst,
    input  wire [1:0] x,
    output wire o0,
    output wire o1,
    output wire o2,
    output wire o3,
    output wire o4,
    output wire o5,
    output wire o6,
    output wire o7,
    output wire o8,
    output wire o9,
    output wire o10,
    output wire o11,
    output wire o12,
    output wire o13,
    output wire o14,
    output wire o15
);

    wire c0 = 1'b0;
    wire c1 = 1'b1;
    // scalar aliases (names match blif.signal_name)
    wire x0 = x[0];
    wire x1 = x[1];

    // gates (topological order)
    wire g0 = 1'b0;
    wire g1 = x0 & x1;
    wire g2 = x0 & ~x1;
    wire g3 = x0;
    wire g4 = ~x0 & x1;
    wire g5 = x1;
    wire g6 = x0 ^ x1;
    wire g7 = x0 | x1;
    wire g8 = ~(x0 | x1);
    wire g9 = ~(x0 ^ x1);
    wire g10 = ~x1;
    wire g11 = x0 | ~x1;
    wire g12 = ~x0;
    wire g13 = ~x0 | x1;
    wire g14 = ~(x0 & x1);
    wire g15 = 1'b1;

    assign o0 = g0;
    assign o1 = g1;
    assign o2 = g2;
    assign o3 = g3;
    assign o4 = g4;
    assign o5 = g5;
    assign o6 = g6;
    assign o7 = g7;
    assign o8 = g8;
    assign o9 = g9;
    assign o10 = g10;
    assign o11 = g11;
    assign o12 = g12;
    assign o13 = g13;
    assign o14 = g14;
    assign o15 = g15;

endmodule
