// generated by export_fsm.py — golden-vector equivalence testbench
`timescale 1ns/1ps
module tb_fsm;
    reg clk = 1'b0;
    reg rst;
    reg  [8:0] x;
    wire [1023:0] q;
    lgn_fsm dut (.clk(clk), .rst(rst), .x(x), .q(q));
    always #5 clk = ~clk;

    reg [1023:0] golden [0:319];
    integer sym, t, errors, sym_errors, pass_count;

    initial begin
        $readmemh("golden_sym0.txt", golden, 0, 39);
        $readmemh("golden_sym1.txt", golden, 40, 79);
        $readmemh("golden_sym2.txt", golden, 80, 119);
        $readmemh("golden_sym3.txt", golden, 120, 159);
        $readmemh("golden_sym4.txt", golden, 160, 199);
        $readmemh("golden_sym5.txt", golden, 200, 239);
        $readmemh("golden_sym6.txt", golden, 240, 279);
        $readmemh("golden_sym7.txt", golden, 280, 319);
        errors = 0;
        pass_count = 0;
        for (sym = 0; sym < 8; sym = sym + 1) begin
            sym_errors = 0;
            // synchronous reset: load net.init
            rst = 1'b1;
            x = 9'b0;
            @(posedge clk); #1;
            if (q !== 1024'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000) begin
                $display("SYM %0d: FAIL at reset", sym);
                sym_errors = sym_errors + 1;
            end
            rst = 1'b0;
            // t=0: the write frame (cue + one-hot symbol)
            x = (9'b1 << sym) | (9'b1 << 8);
            @(posedge clk); #1;
            x = 9'b0;                 // forced blanks afterwards
            for (t = 0; t < 40; t = t + 1) begin
                if (t > 0) begin @(posedge clk); #1; end
                if (q !== golden[sym * 40 + t]) begin
                    sym_errors = sym_errors + 1;
                    if (sym_errors <= 3)
                        $display("SYM %0d: MISMATCH frame %0d", sym, t);
                end
            end
            if (sym_errors == 0) begin
                $display("SYM %0d: PASS (40/40 frames)", sym);
                pass_count = pass_count + 1;
            end else
                $display("SYM %0d: FAIL (%0d bad frames)", sym, sym_errors);
            errors = errors + sym_errors;
        end
        $display("EQUIV: %0d/8 symbols PASS, %0d frame mismatches", pass_count, errors);
        if (pass_count == 8 && errors == 0)
            $display("RESULT: PASS");
        else
            $display("RESULT: FAIL");
        $finish;
    end
endmodule
