// generated by export_fsm.py — exhaustive check of the 16 gate ops
`timescale 1ns/1ps
module tb_ops;
    reg clk = 1'b0, rst = 1'b0;
    reg [1:0] x;
    wire [15:0] obus;
    wire o0, o1, o2, o3, o4, o5, o6, o7, o8, o9, o10, o11, o12, o13, o14, o15;
    lgn_ops dut (.clk(clk), .rst(rst), .x(x), .o0(o0), .o1(o1), .o2(o2), .o3(o3), .o4(o4), .o5(o5), .o6(o6), .o7(o7), .o8(o8), .o9(o9), .o10(o10), .o11(o11), .o12(o12), .o13(o13), .o14(o14), .o15(o15));
    assign obus = {o15, o14, o13, o12, o11, o10, o9, o8, o7, o6, o5, o4, o3, o2, o1, o0};
    integer errors;
    initial begin
        errors = 0;
        x = 2'd0; #1;
        if (obus !== 16'hff00) begin
            $display("OPS: case a=%0d b=%0d got %h want ff00", x[0], x[1], obus);
            errors = errors + 1;
        end
        x = 2'd1; #1;
        if (obus !== 16'hcccc) begin
            $display("OPS: case a=%0d b=%0d got %h want cccc", x[0], x[1], obus);
            errors = errors + 1;
        end
        x = 2'd2; #1;
        if (obus !== 16'hf0f0) begin
            $display("OPS: case a=%0d b=%0d got %h want f0f0", x[0], x[1], obus);
            errors = errors + 1;
        end
        x = 2'd3; #1;
        if (obus !== 16'haaaa) begin
            $display("OPS: case a=%0d b=%0d got %h want aaaa", x[0], x[1], obus);
            errors = errors + 1;
        end
        if (errors == 0)
            $display("OPS: 4/4 cases PASS");
        else
            $display("OPS: FAIL (%0d cases)", errors);
        $finish;
    end
endmodule
