// generated by export_top.py — class-level golden-vector testbench
`timescale 1ns/1ps
module tb_top;
    reg clk = 1'b0;
    reg rst;
    reg  [8:0] x;
    wire [2:0] class_out;
    lgn_top dut (.clk(clk), .rst(rst), .x(x), .class_out(class_out));
    always #5 clk = ~clk;

    reg [3:0] golden_cls [0:319];
`ifdef RTL_Q_CHECK
    reg [1023:0] golden_q [0:319];
    integer q_errors;
`endif
    integer sym, t, errors, sym_errors, pass_count;

    initial begin
        $readmemh("golden_cls_sym0.txt", golden_cls, 0, 39);
        $readmemh("golden_cls_sym1.txt", golden_cls, 40, 79);
        $readmemh("golden_cls_sym2.txt", golden_cls, 80, 119);
        $readmemh("golden_cls_sym3.txt", golden_cls, 120, 159);
        $readmemh("golden_cls_sym4.txt", golden_cls, 160, 199);
        $readmemh("golden_cls_sym5.txt", golden_cls, 200, 239);
        $readmemh("golden_cls_sym6.txt", golden_cls, 240, 279);
        $readmemh("golden_cls_sym7.txt", golden_cls, 280, 319);
`ifdef RTL_Q_CHECK
        $readmemh("golden_sym0.txt", golden_q, 0, 39);
        $readmemh("golden_sym1.txt", golden_q, 40, 79);
        $readmemh("golden_sym2.txt", golden_q, 80, 119);
        $readmemh("golden_sym3.txt", golden_q, 120, 159);
        $readmemh("golden_sym4.txt", golden_q, 160, 199);
        $readmemh("golden_sym5.txt", golden_q, 200, 239);
        $readmemh("golden_sym6.txt", golden_q, 240, 279);
        $readmemh("golden_sym7.txt", golden_q, 280, 319);
        q_errors = 0;
`endif
        errors = 0;
        pass_count = 0;
        for (sym = 0; sym < 8; sym = sym + 1) begin
            sym_errors = 0;
            // synchronous reset: load net.init
            rst = 1'b1;
            x = 9'b0;
            @(posedge clk); #1;
            // reset-state decode (simulator-computed, first-max tie-break)
            if (class_out !== 3'd0) begin
                $display("SYM %0d: FAIL at reset (class_out=%0d)", sym, class_out);
                sym_errors = sym_errors + 1;
            end
`ifdef RTL_Q_CHECK
            if (dut.q !== 1024'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000) begin
                $display("SYM %0d: Q FAIL at reset", sym);
                q_errors = q_errors + 1;
            end
`endif
            rst = 1'b0;
            // t=0: the write frame (cue + one-hot symbol)
            x = (9'b1 << sym) | (9'b1 << 8);
            @(posedge clk); #1;
            x = 9'b0;                 // forced blanks afterwards
            for (t = 0; t < 40; t = t + 1) begin
                if (t > 0) begin @(posedge clk); #1; end
                if (class_out !== golden_cls[sym * 40 + t][2:0]) begin
                    sym_errors = sym_errors + 1;
                    if (sym_errors <= 3)
                        $display("SYM %0d: CLASS MISMATCH frame %0d (got %0d want %0d)", sym, t, class_out, golden_cls[sym * 40 + t][2:0]);
                end
`ifdef RTL_Q_CHECK
                if (dut.q !== golden_q[sym * 40 + t]) begin
                    q_errors = q_errors + 1;
                    if (q_errors <= 3)
                        $display("SYM %0d: Q MISMATCH frame %0d", sym, t);
                end
`endif
            end
            if (sym_errors == 0) begin
                $display("SYM %0d: PASS (40/40 frames)", sym);
                pass_count = pass_count + 1;
            end else
                $display("SYM %0d: FAIL (%0d bad frames)", sym, sym_errors);
            errors = errors + sym_errors;
        end
`ifdef RTL_Q_CHECK
        $display("QCHECK: %0d q-frame mismatches", q_errors);
        errors = errors + q_errors;
`endif
        $display("EQUIV: %0d/8 symbols PASS, %0d frame mismatches", pass_count, errors);
        if (pass_count == 8 && errors == 0)
            $display("RESULT: PASS");
        else
            $display("RESULT: FAIL");
        $finish;
    end
endmodule
