"""
verilog.py — emit a Netlist as synthesizable Verilog-2001.
==========================================================

One continuous ``assign`` per gate implementing the exact ``ir.GATE_FN`` semantics
(the 16 two-input difflogic ops, truth-table bit order AB=00,01,10,11 — note the
asymmetric ops: 2 = a&~b, 4 = ~a&b, 11 = a|~b, 13 = ~a|b). Registers update on
``posedge clk``; a synchronous ``rst`` loads ``net.init``.

Interface (module ``lgn_fsm`` by default)::

    input  wire clk, rst;
    input  wire [n_pi-1:0]    x;    // one input vector per clock step
    output reg  [n_state-1:0] q;    // the state register file
    output wire o<i>;               // one scalar port per Netlist output, if any

Deployable-top variants (defaults preserve the historical output byte-for-byte —
gated by regenerating ``synth/fsm.v`` and diffing):

    expose_q=False   q becomes an INTERNAL ``reg [n_state-1:0] q`` (no port);
                     aliases, always-block and init literal are unchanged.
    out_bus="name"   the outputs become ONE vector port
                     ``output wire [len(outputs)-1:0] name`` (bit i = output i)
                     instead of the scalar ``o<i>`` ports.

Internal signal names match ``blif.signal_name`` exactly (``c0``/``c1``, ``x<i>``,
``q<i>``, ``g<i>``) so the Verilog, the BLIF, and the ABC logs can be cross-read:
``x<i>``/``q<i>`` are scalar wire aliases of ``x[i]``/``q[i]``. Gates whose op is
FALSE/TRUE (0/15) are emitted as constants and ignore their fanins, mirroring
``blif.emit_blif``.

Simulation semantics match ``sim.step``: with the state at h_t and x applied,
the next active clock edge loads h_{t+1} = f(x, h_t) into q.
"""

from __future__ import annotations

from .blif import signal_name
from .ir import Netlist

# op id -> Verilog expression over fanin names {a}, {b} (mirrors ir.GATE_FN)
VERILOG_EXPR = {
    0: "1'b0",
    1: "{a} & {b}",
    2: "{a} & ~{b}",
    3: "{a}",
    4: "~{a} & {b}",
    5: "{b}",
    6: "{a} ^ {b}",
    7: "{a} | {b}",
    8: "~({a} | {b})",
    9: "~({a} ^ {b})",
    10: "~{b}",
    11: "{a} | ~{b}",
    12: "~{a}",
    13: "~{a} | {b}",
    14: "~({a} & {b})",
    15: "1'b1",
}


def emit_verilog(net: Netlist, path: str, module: str = "lgn_fsm",
                 expose_q: bool = True, out_bus: str | None = None) -> None:
    nm = lambda s: signal_name(net, int(s))  # noqa: E731
    L: list[str] = []
    L.append(f"// generated by mlgn.netlist.verilog — {net.n_pi} PIs, "
             f"{net.n_state} state bits, {net.n_gates} gates, "
             f"{len(net.outputs)} outputs")
    L.append(f"module {module} (")
    ports = ["    input  wire clk",
             "    input  wire rst",
             f"    input  wire [{net.n_pi - 1}:0] x"]
    if net.n_state and expose_q:
        ports.append(f"    output reg  [{net.n_state - 1}:0] q")
    if out_bus is None:
        ports += [f"    output wire o{i}" for i in range(len(net.outputs))]
    else:
        assert net.outputs, "out_bus requires at least one output"
        ports.append(f"    output wire [{len(net.outputs) - 1}:0] {out_bus}")
    L.append(",\n".join(ports))
    L.append(");")
    L.append("")
    if net.n_state and not expose_q:
        L.append(f"    reg  [{net.n_state - 1}:0] q;    "
                 "// state register file (internal, not a port)")
        L.append("")
    L.append("    wire c0 = 1'b0;")
    L.append("    wire c1 = 1'b1;")
    L.append("    // scalar aliases (names match blif.signal_name)")
    for i in range(net.n_pi):
        L.append(f"    wire x{i} = x[{i}];")
    for i in range(net.n_state):
        L.append(f"    wire q{i} = q[{i}];")
    L.append("")
    L.append("    // gates (topological order)")
    for g in range(net.n_gates):
        op = int(net.ops[g])
        expr = VERILOG_EXPR[op]
        if op not in (0, 15):
            expr = expr.format(a=nm(net.src_a[g]), b=nm(net.src_b[g]))
        L.append(f"    wire g{g} = {expr};")
    L.append("")
    if net.n_state:
        init_bits = "".join(str(int(net.init[i]))
                            for i in range(net.n_state - 1, -1, -1))
        L.append("    // state registers: synchronous reset to net.init")
        L.append("    always @(posedge clk) begin")
        L.append("        if (rst) begin")
        L.append(f"            q <= {net.n_state}'b{init_bits};")
        L.append("        end else begin")
        for i, ns in enumerate(net.next_state):
            L.append(f"            q[{i}] <= {nm(ns)};")
        L.append("        end")
        L.append("    end")
        L.append("")
    for i, s in enumerate(net.outputs):
        if out_bus is None:
            L.append(f"    assign o{i} = {nm(s)};")
        else:
            L.append(f"    assign {out_bus}[{i}] = {nm(s)};")
    if net.outputs:
        L.append("")
    L.append("endmodule")
    with open(path, "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
